# Generated by Django 5.1.7 on 2025-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyValveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('sample_time', models.DateTimeField()),
                ('t1_remote_k', models.FloatField(blank=True, null=True)),
                ('t2_embeded_k', models.FloatField(blank=True, null=True)),
                ('delta_t_k', models.FloatField(blank=True, null=True)),
                ('flow_volume_total_m3', models.FloatField(blank=True, null=True)),
                ('operating_hours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id'], name='dashboard_e_device__a16ff6_idx'), models.Index(fields=['sample_time'], name='dashboard_e_sample__29eecd_idx')],
            },
        ),
    ]
